language: node_js
node_js:
  - "6"   # test backwards compatibility
  - node  # latest stable

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build

before_deploy:
  # create zipfile for release
  - zip modelleertaal-$TRAVIS_TAG.zip index.html config.js scripts/* modellen/*
  # create folder to deploy to gh-pages
  - git worktree add _build gh-pages  # fetch current gh-pages
  - mkdir -p _build/dev
  - if [[ "$TRAVIS_TAG" ]]; then echo "Deploying release"; export BUILD_DIR=_build/; else echo "Deploying dev branch"; export BUILD_DIR=_build/dev; fi
  - cp index.html config.js $BUILD_DIR
  - cp -R scripts $BUILD_DIR
  - cp -R modellen $BUILD_DIR
  - touch _build/.nojekyll

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _build
    on:
      branch: master
      node_js: node
  - provider: releases
    file:
      - modelleertaal-$TRAVIS_TAG.zip
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      branch: master
      node_js: node
      tags: true
