language: node_js
node_js:
  - "6"   # test backwards compatibility
  - node  # latest stable

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build

before_deploy:
  # only ignore installed npm modules. Keep build.
  - echo "node_modules" >.gitignore
  # create zipfile for release
  - zip modelleertaal-$TRAVIS_TAG.zip index.html scripts/* modellen/*

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node_js: node
  - provider: releases
    file:
      - modelleertaal-$TRAVIS_TAG.zip
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      branch: master
      node_js: node
      tags: true
