language: node_js
node_js:
  #- "0.10"
  - "6"
  - "7"

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build

before_deploy:
  # only ignore installed npm modules. Keep build.
  - echo "node_modules" >.gitignore

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node_js: "7"
  - provider: releases
    file:
      - index.html
      - scripts/*
      - modelllen/*
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      branch: master
      node_js: "7"
      tags: true
